// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: merlion/ve/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryTotalVotingPowerRequest struct {
	AtTime  uint64 `protobuf:"varint,1,opt,name=at_time,json=atTime,proto3" json:"at_time,omitempty"`
	AtBlock int64  `protobuf:"varint,2,opt,name=at_block,json=atBlock,proto3" json:"at_block,omitempty"`
}

func (m *QueryTotalVotingPowerRequest) Reset()         { *m = QueryTotalVotingPowerRequest{} }
func (m *QueryTotalVotingPowerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTotalVotingPowerRequest) ProtoMessage()    {}
func (*QueryTotalVotingPowerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_256fa148a9e7f65f, []int{0}
}
func (m *QueryTotalVotingPowerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalVotingPowerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalVotingPowerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalVotingPowerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalVotingPowerRequest.Merge(m, src)
}
func (m *QueryTotalVotingPowerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalVotingPowerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalVotingPowerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalVotingPowerRequest proto.InternalMessageInfo

func (m *QueryTotalVotingPowerRequest) GetAtTime() uint64 {
	if m != nil {
		return m.AtTime
	}
	return 0
}

func (m *QueryTotalVotingPowerRequest) GetAtBlock() int64 {
	if m != nil {
		return m.AtBlock
	}
	return 0
}

type QueryTotalVotingPowerResponse struct {
	Power github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=power,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"power"`
}

func (m *QueryTotalVotingPowerResponse) Reset()         { *m = QueryTotalVotingPowerResponse{} }
func (m *QueryTotalVotingPowerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTotalVotingPowerResponse) ProtoMessage()    {}
func (*QueryTotalVotingPowerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_256fa148a9e7f65f, []int{1}
}
func (m *QueryTotalVotingPowerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalVotingPowerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalVotingPowerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalVotingPowerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalVotingPowerResponse.Merge(m, src)
}
func (m *QueryTotalVotingPowerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalVotingPowerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalVotingPowerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalVotingPowerResponse proto.InternalMessageInfo

type QueryVotingPowerRequest struct {
	VeId    string `protobuf:"bytes,1,opt,name=ve_id,json=veId,proto3" json:"ve_id,omitempty"`
	AtTime  uint64 `protobuf:"varint,2,opt,name=at_time,json=atTime,proto3" json:"at_time,omitempty"`
	AtBlock int64  `protobuf:"varint,3,opt,name=at_block,json=atBlock,proto3" json:"at_block,omitempty"`
}

func (m *QueryVotingPowerRequest) Reset()         { *m = QueryVotingPowerRequest{} }
func (m *QueryVotingPowerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVotingPowerRequest) ProtoMessage()    {}
func (*QueryVotingPowerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_256fa148a9e7f65f, []int{2}
}
func (m *QueryVotingPowerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVotingPowerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVotingPowerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVotingPowerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVotingPowerRequest.Merge(m, src)
}
func (m *QueryVotingPowerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVotingPowerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVotingPowerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVotingPowerRequest proto.InternalMessageInfo

func (m *QueryVotingPowerRequest) GetVeId() string {
	if m != nil {
		return m.VeId
	}
	return ""
}

func (m *QueryVotingPowerRequest) GetAtTime() uint64 {
	if m != nil {
		return m.AtTime
	}
	return 0
}

func (m *QueryVotingPowerRequest) GetAtBlock() int64 {
	if m != nil {
		return m.AtBlock
	}
	return 0
}

type QueryVotingPowerResponse struct {
	Power github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=power,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"power"`
}

func (m *QueryVotingPowerResponse) Reset()         { *m = QueryVotingPowerResponse{} }
func (m *QueryVotingPowerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVotingPowerResponse) ProtoMessage()    {}
func (*QueryVotingPowerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_256fa148a9e7f65f, []int{3}
}
func (m *QueryVotingPowerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVotingPowerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVotingPowerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVotingPowerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVotingPowerResponse.Merge(m, src)
}
func (m *QueryVotingPowerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVotingPowerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVotingPowerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVotingPowerResponse proto.InternalMessageInfo

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_256fa148a9e7f65f, []int{4}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_256fa148a9e7f65f, []int{5}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func init() {
	proto.RegisterType((*QueryTotalVotingPowerRequest)(nil), "merlion.ve.v1.QueryTotalVotingPowerRequest")
	proto.RegisterType((*QueryTotalVotingPowerResponse)(nil), "merlion.ve.v1.QueryTotalVotingPowerResponse")
	proto.RegisterType((*QueryVotingPowerRequest)(nil), "merlion.ve.v1.QueryVotingPowerRequest")
	proto.RegisterType((*QueryVotingPowerResponse)(nil), "merlion.ve.v1.QueryVotingPowerResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "merlion.ve.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "merlion.ve.v1.QueryParamsResponse")
}

func init() { proto.RegisterFile("merlion/ve/v1/query.proto", fileDescriptor_256fa148a9e7f65f) }

var fileDescriptor_256fa148a9e7f65f = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0x6e, 0xfa, 0x35, 0xf0, 0x84, 0x84, 0xbc, 0x4d, 0xed, 0xca, 0x96, 0x6d, 0x99, 0x18, 0x63,
	0x63, 0xb1, 0xba, 0xfd, 0x83, 0x6a, 0x97, 0x71, 0x1a, 0xd1, 0xc4, 0x81, 0x4b, 0x71, 0xda, 0x57,
	0xc1, 0x5a, 0x63, 0x67, 0xb1, 0x1b, 0x18, 0x88, 0x0b, 0x57, 0x2e, 0x48, 0x5c, 0x38, 0xf2, 0x73,
	0x76, 0x9c, 0xc4, 0x05, 0x71, 0x98, 0x50, 0xcb, 0x0f, 0x41, 0xb1, 0x2d, 0xd4, 0x94, 0x6e, 0x70,
	0xd8, 0x29, 0x89, 0xfd, 0xbc, 0xcf, 0x87, 0xfd, 0x04, 0x2d, 0xc7, 0x90, 0x0e, 0x98, 0xe0, 0x24,
	0x03, 0x92, 0xb5, 0xc9, 0xd9, 0x10, 0xd2, 0x73, 0x3f, 0x49, 0x85, 0x12, 0xf8, 0x9e, 0xdd, 0xf2,
	0x33, 0xf0, 0xb3, 0x76, 0x6b, 0x31, 0x12, 0x91, 0xd0, 0x3b, 0x24, 0x7f, 0x33, 0xa0, 0xd6, 0x4a,
	0x24, 0x44, 0x34, 0x00, 0x42, 0x13, 0x46, 0x28, 0xe7, 0x42, 0x51, 0xc5, 0x04, 0x97, 0x76, 0x77,
	0xa7, 0x27, 0x64, 0x2c, 0x24, 0x09, 0xa9, 0x04, 0xc3, 0x4d, 0xb2, 0x76, 0x08, 0x8a, 0xb6, 0x49,
	0x42, 0x23, 0xc6, 0x35, 0xd8, 0x62, 0x1f, 0x14, 0x9d, 0x44, 0xc0, 0x41, 0x32, 0x4b, 0xe4, 0x05,
	0x68, 0xe5, 0x59, 0x3e, 0x7e, 0x22, 0x14, 0x1d, 0x3c, 0x17, 0x8a, 0xf1, 0xe8, 0x58, 0xbc, 0x86,
	0x34, 0x80, 0xb3, 0x21, 0x48, 0x85, 0x1b, 0x68, 0x8e, 0xaa, 0xae, 0x62, 0x31, 0x34, 0x9d, 0x75,
	0x67, 0xbb, 0x1a, 0xd4, 0xa9, 0x3a, 0x61, 0x31, 0xe0, 0x65, 0x74, 0x87, 0xaa, 0x6e, 0x38, 0x10,
	0xbd, 0xd3, 0x66, 0x79, 0xdd, 0xd9, 0xae, 0x04, 0x73, 0x54, 0x75, 0xf2, 0x4f, 0x0f, 0xd0, 0xea,
	0x35, 0x9c, 0x32, 0x11, 0x5c, 0x02, 0x3e, 0x44, 0xb5, 0x24, 0x5f, 0xd0, 0x94, 0x77, 0x3b, 0xfe,
	0xc5, 0xd5, 0x5a, 0xe9, 0xc7, 0xd5, 0xda, 0x56, 0xc4, 0xd4, 0xab, 0x61, 0xe8, 0xf7, 0x44, 0x4c,
	0x6c, 0x3e, 0xf3, 0xd8, 0x93, 0xfd, 0x53, 0xa2, 0xce, 0x13, 0x90, 0xfe, 0x11, 0x57, 0x81, 0x19,
	0xf6, 0x42, 0xd4, 0xd0, 0x32, 0x33, 0x5c, 0x2f, 0xa0, 0x5a, 0x06, 0x5d, 0xd6, 0x37, 0x02, 0x41,
	0x35, 0x83, 0xa3, 0xfe, 0x64, 0x94, 0xf2, 0xb5, 0x51, 0x2a, 0xc5, 0x28, 0x2f, 0x51, 0xf3, 0x6f,
	0x8d, 0x5b, 0x4d, 0xb1, 0x88, 0xb0, 0x56, 0x38, 0xa6, 0x29, 0x8d, 0xa5, 0x0d, 0xe0, 0x3d, 0x45,
	0x0b, 0x85, 0x55, 0x2b, 0x79, 0x80, 0xea, 0x89, 0x5e, 0xd1, 0x9a, 0xf3, 0xfb, 0x4b, 0x7e, 0xa1,
	0x4a, 0xbe, 0x81, 0x77, 0xaa, 0xb9, 0x95, 0xc0, 0x42, 0xf7, 0xbf, 0x56, 0x50, 0x4d, 0x93, 0xe1,
	0x2f, 0x0e, 0xba, 0x3f, 0x7d, 0x29, 0x78, 0x77, 0x8a, 0xe3, 0xa6, 0x3a, 0xb4, 0x9e, 0xfc, 0x1f,
	0xd8, 0xd8, 0xf5, 0x1e, 0x7f, 0xf8, 0xf6, 0xeb, 0x73, 0x79, 0x13, 0x6f, 0x90, 0x62, 0x05, 0x55,
	0x3e, 0xd0, 0xcd, 0xf4, 0x44, 0x57, 0x1f, 0x03, 0xfe, 0xe8, 0xa0, 0xf9, 0x49, 0x57, 0x5b, 0xb3,
	0x84, 0x66, 0x18, 0x7a, 0xf4, 0x4f, 0x9c, 0xf5, 0xb2, 0xab, 0xbd, 0x3c, 0xc4, 0x9b, 0x53, 0x5e,
	0x26, 0x5d, 0x90, 0x77, 0xba, 0x35, 0xef, 0x31, 0x47, 0x75, 0x73, 0x94, 0x78, 0x63, 0x16, 0x7f,
	0xe1, 0xae, 0x5a, 0xde, 0x4d, 0x10, 0xab, 0xbe, 0xaa, 0xd5, 0x1b, 0x78, 0x69, 0x4a, 0xdd, 0x5c,
	0x51, 0xe7, 0xf0, 0x62, 0xe4, 0x3a, 0x97, 0x23, 0xd7, 0xf9, 0x39, 0x72, 0x9d, 0x4f, 0x63, 0xb7,
	0x74, 0x39, 0x76, 0x4b, 0xdf, 0xc7, 0x6e, 0xe9, 0xc5, 0xce, 0x44, 0x9b, 0xec, 0xe8, 0xde, 0x5b,
	0xc1, 0xe1, 0x0f, 0xcf, 0x9b, 0x9c, 0x49, 0xb7, 0x2a, 0xac, 0xeb, 0x5f, 0xfa, 0xe0, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xff, 0x10, 0x81, 0x35, 0x7b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// TotalVotingPower queries the total voting power.
	TotalVotingPower(ctx context.Context, in *QueryTotalVotingPowerRequest, opts ...grpc.CallOption) (*QueryTotalVotingPowerResponse, error)
	// VotingPower queries the voting power of a veNFT.
	VotingPower(ctx context.Context, in *QueryVotingPowerRequest, opts ...grpc.CallOption) (*QueryVotingPowerResponse, error)
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) TotalVotingPower(ctx context.Context, in *QueryTotalVotingPowerRequest, opts ...grpc.CallOption) (*QueryTotalVotingPowerResponse, error) {
	out := new(QueryTotalVotingPowerResponse)
	err := c.cc.Invoke(ctx, "/merlion.ve.v1.Query/TotalVotingPower", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VotingPower(ctx context.Context, in *QueryVotingPowerRequest, opts ...grpc.CallOption) (*QueryVotingPowerResponse, error) {
	out := new(QueryVotingPowerResponse)
	err := c.cc.Invoke(ctx, "/merlion.ve.v1.Query/VotingPower", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/merlion.ve.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// TotalVotingPower queries the total voting power.
	TotalVotingPower(context.Context, *QueryTotalVotingPowerRequest) (*QueryTotalVotingPowerResponse, error)
	// VotingPower queries the voting power of a veNFT.
	VotingPower(context.Context, *QueryVotingPowerRequest) (*QueryVotingPowerResponse, error)
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) TotalVotingPower(ctx context.Context, req *QueryTotalVotingPowerRequest) (*QueryTotalVotingPowerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalVotingPower not implemented")
}
func (*UnimplementedQueryServer) VotingPower(ctx context.Context, req *QueryVotingPowerRequest) (*QueryVotingPowerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VotingPower not implemented")
}
func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_TotalVotingPower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTotalVotingPowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TotalVotingPower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merlion.ve.v1.Query/TotalVotingPower",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TotalVotingPower(ctx, req.(*QueryTotalVotingPowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VotingPower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVotingPowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VotingPower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merlion.ve.v1.Query/VotingPower",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VotingPower(ctx, req.(*QueryVotingPowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merlion.ve.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "merlion.ve.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TotalVotingPower",
			Handler:    _Query_TotalVotingPower_Handler,
		},
		{
			MethodName: "VotingPower",
			Handler:    _Query_VotingPower_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merlion/ve/v1/query.proto",
}

func (m *QueryTotalVotingPowerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalVotingPowerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalVotingPowerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AtBlock != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AtBlock))
		i--
		dAtA[i] = 0x10
	}
	if m.AtTime != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AtTime))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryTotalVotingPowerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalVotingPowerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalVotingPowerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Power.Size()
		i -= size
		if _, err := m.Power.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryVotingPowerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVotingPowerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVotingPowerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AtBlock != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AtBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.AtTime != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AtTime))
		i--
		dAtA[i] = 0x10
	}
	if len(m.VeId) > 0 {
		i -= len(m.VeId)
		copy(dAtA[i:], m.VeId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.VeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVotingPowerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVotingPowerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVotingPowerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Power.Size()
		i -= size
		if _, err := m.Power.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryTotalVotingPowerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AtTime != 0 {
		n += 1 + sovQuery(uint64(m.AtTime))
	}
	if m.AtBlock != 0 {
		n += 1 + sovQuery(uint64(m.AtBlock))
	}
	return n
}

func (m *QueryTotalVotingPowerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Power.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryVotingPowerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VeId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AtTime != 0 {
		n += 1 + sovQuery(uint64(m.AtTime))
	}
	if m.AtBlock != 0 {
		n += 1 + sovQuery(uint64(m.AtBlock))
	}
	return n
}

func (m *QueryVotingPowerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Power.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryTotalVotingPowerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalVotingPowerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalVotingPowerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AtTime", wireType)
			}
			m.AtTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AtTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AtBlock", wireType)
			}
			m.AtBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AtBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalVotingPowerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalVotingPowerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalVotingPowerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Power.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVotingPowerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVotingPowerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVotingPowerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AtTime", wireType)
			}
			m.AtTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AtTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AtBlock", wireType)
			}
			m.AtBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AtBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVotingPowerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVotingPowerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVotingPowerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Power.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
